//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [Serializable]
    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public int idCate { get; set; }
        [Display(Name = "Tên Loại")]
        public string nameCate { get; set; }
        [Display(Name = "Tên Ảnh")]
        public string coverCate { get; set; }
        [Display(Name = "Icon")]
        public string iconCate { get; set; }
        [Display(Name = "Giới tính")]
        public string moreCate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
