//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    [Serializable]
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.ORDER = new HashSet<ORDER>();
        }
    
        public int idCus { get; set; }
        [Display(Name = "Tên khách hàng")]
        public string nameCus { get; set; }
        [Display(Name = "Email")]
        public string emailCus { get; set; }
        [Display(Name = "Mật khẩu")]
        public string passCus { get; set; }
        [Display(Name = "Địa chỉ")]
        public string AdressCus { get; set; }
        [Display(Name = "Điện thoại")]
        public string phoneCus { get; set; }
        [Display(Name = "Ảnh")]
        public string avaCus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<ORDER> ORDER { get; set; }
    }
}
