//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothesStore.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [Serializable]
    public partial class ORDERDETAILS
    {
        public int idOrdDe { get; set; }
        [Display(Name = "Giá ðõn")]
        public int unitPriceOrdDe { get; set; }
        [Display(Name = "Tên ")]
        public Nullable<int> ORDER_idOrd { get; set; }
        [Display(Name = "Tên khách hàng")]
        public Nullable<int> PRODUCT_idPro { get; set; }
        [Display(Name = "Tên khách hàng")]
        public virtual ORDER ORDER { get; set; }
        [Display(Name = "Tên khách hàng")]
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
